lib/uprobot_web/router.ex
defmodule UprobotWeb.Router do
  @moduledoc false

  use UprobotWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UprobotWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/sites", SiteController do
      resources "/statuses", StatusController, only: [:delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", UprobotWeb do
  #   pipe_through :api
  # end
end

lib/uprobot_web/views/layout_view.ex
defmodule UprobotWeb.LayoutView do
  use UprobotWeb, :view
end

lib/uprobot_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Uprobot</title>

    <link rel="stylesheet" href='<%= Routes.static_path(@conn, "/css/app.css") %>'/>
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container" style="padding: 0 1rem;">
        <div class="navbar-brand">
          <a class="navbar-item" href='<%= Routes.page_path(@conn, :index) %>'>
            <img src='<%= Routes.static_path(@conn, "/images/logo.jpg") %>' />
          </a>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href='<%= Routes.site_path(@conn, :index) %>'>
              Sites
            </a>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light">
                  Log in
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="container" style="margin-top: 2rem; padding: 0 1rem;">
      <%= unless is_nil(get_flash(@conn, :info)) do %>
        <p class="notification is-info"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= unless is_nil(get_flash(@conn, :error)) do %>
        <p class="notification is-danger"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>