lib/uprobot_web/router.ex
defmodule UprobotWeb.Router do
  @moduledoc false

  use UprobotWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UprobotWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/sites", SiteController do
      resources "/statuses", StatusController, only: [:delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", UprobotWeb do
  #   pipe_through :api
  # end
end

lib/uprobot/monit/site.ex
defmodule Uprobot.Monit.Site do
  @moduledoc false

  use Ecto.Schema
  import Ecto.Changeset

  schema "sites" do
    field :name, :string
    field :url, :string
    field :interval, :integer
    field :method, :string
    field :is_active, :boolean, default: false
    field :verified_at, :naive_datetime

    has_many :statuses, Uprobot.Monit.Status

    timestamps()
  end

  @doc false
  def changeset(site, attrs) do
    site
    |> cast(attrs, [:name, :url, :interval, :method, :is_active, :verified_at])
    |> validate_required([:name, :url, :interval, :method, :is_active])
    |> unique_constraint(:url)
  end
end

lib/uprobot_web/controllers/site_controller.ex
defmodule UprobotWeb.SiteController do
  @moduledoc false
  use UprobotWeb, :controller

  alias Uprobot.Monit
  alias Uprobot.Monit.Site

  def index(conn, _params) do
    sites = Monit.list_sites()
    render(conn, "index.html", sites: sites)
  end

  def new(conn, _params) do
    changeset = Monit.change_site(%Site{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"site" => site_params}) do
    case Monit.create_site(site_params) do
      {:ok, site} ->
        conn
        |> put_flash(:info, "Site created successfully.")
        |> redirect(to: Routes.site_path(conn, :show, site))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    site = Monit.get_site!(id, 300)
    render(conn, "show.html", site: site)
  end

  def edit(conn, %{"id" => id}) do
    site = Monit.get_site!(id)
    changeset = Monit.change_site(site)
    render(conn, "edit.html", site: site, changeset: changeset)
  end

  def update(conn, %{"id" => id, "site" => site_params}) do
    site = Monit.get_site!(id)

    case Monit.update_site(site, site_params) do
      {:ok, site} ->
        conn
        |> put_flash(:info, "Site updated successfully.")
        |> redirect(to: Routes.site_path(conn, :show, site))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", site: site, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    site = Monit.get_site!(id)
    {:ok, _site} = Monit.delete_site(site)

    conn
    |> put_flash(:info, "Site deleted successfully.")
    |> redirect(to: Routes.site_path(conn, :index))
  end
end

lib/uprobot_web/views/site_view.ex
defmodule UprobotWeb.SiteView do
  use UprobotWeb, :view
end

lib/uprobot_web/templates/site/edit.html.eex
<h1 class="is-size-3">Edit Site</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.site_path(@conn, :update, @site)) %>

lib/uprobot_web/templates/site/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <label class="label">
      <%= label f, :name %>
    </label>
    <div class="control">
      <%= text_input f, :name, class: "input" %>
      <%= error_tag f, :name %>
    </div>
  </div>

  <div class="columns">
    <div class="column is-2">
      <div class="field">
        <label class="label">
          <%= label f, :method %>
        </label>
        <div class="control">
          <div class="select" style="width: 100%">
            <%= select f, :method, ["get", "options", "head"], style: "width: 100%" %>
          </div>
          <%= error_tag f, :method %>
        </div>
      </div>
    </div>

    <div class="column is-10">
      <div class="field">
        <label class="label">
          <%= label f, :url %>
        </label>
        <div class="control">
          <%= text_input f, :url, class: "input" %>
          <%= error_tag f, :url %>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <label class="label">
      <%= label f, :interval %>
    </label>
    <div class="control">
      <%= number_input f, :interval, class: "input", value: 100 %>
      <%= error_tag f, :interval %>
    </div>
  </div>

  <div class="columns">
    <div class="column is-2">
      <div class="field">
        <%= radio_button f, :is_active, true, class: "is-checkradio" %>
        <label for="site_is_active_true">Active</label>
      </div>
    </div>
    <div class="column is-2">
      <div class="field">
        <%= radio_button f, :is_active, false, class: "is-checkradio" %>
        <label for="site_is_active_false">Passive</label>
      </div>
    </div>
  </div>

  <div>
    <%= submit "Save", class: "button is-primary" %>
    <%= link "Back", to: Routes.site_path(@conn, :index), class: "button is-dark" %>
  </div>
<% end %>

lib/uprobot_web/templates/site/index.html.eex
<h1 class="is-size-3">
  Sites
  <span class="is-pulled-right"><%= link "New Site", to: Routes.site_path(@conn, :new), class: "button is-primary" %></span>
</h1>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>Name</th>
      <th style="text-align: center">Is active?</th>
      <th style="text-align: center">Interval</th>
      <th style="text-align: center">Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for site <- @sites do %>
      <tr>
        <td>
          <a href='<%= Routes.site_path(@conn, :show, site) %>'>
            <%= site.name %>
          </a>

          <br>

          <a href='<%= site.url %>' target="_blank" style="color: #333">
            <small>
              <%= site.url %>
            </small>
          </a>
        </td>
        <td style="vertical-align: middle; text-align: center">
          <%= if site.is_active do %>
            <span class="icon has-text-success tooltip" data-tooltip="Workers enabled!">
              <i class="fas fa-check-square"></i>
            </span>
          <% else %>
            <span class="icon has-text-danger tooltip" data-tooltip="Workers disabled!">
              <i class="fas fa-ban"></i>
            </span>
          <% end %>
        </td>
        <td style="vertical-align: middle; text-align: center">
          <span class="tooltip" data-tooltip="milliseconds"><%= site.interval %></span>
        </td>
        <td style="vertical-align: middle; text-align: center">
          <%= length site.statuses %>
          <%= if length(site.statuses) > 0 do %>
            <% status = hd(site.statuses) %>
            <%= if Map.get(status, :status_code) in 100..300 do %>
              <span class="icon has-text-success tooltip" data-tooltip="<%= Map.get(status, :status_text) %>">
                <i class="fas fa-thumbs-up"></i>
              </span>
            <% else %>
              <span class="icon has-text-danger tooltip" data-tooltip="<%= Map.get(status, :status_text) %>">
                <i class="fas fa-thumbs-down"></i>
              </span>
            <% end %>
          <% else %>
            <span class="icon has-text-info tooltip" data-tooltip="Not known!">
              <i class="fa fa-question"></i>
            </span>
          <% end %>
        </td>

        <td style="vertical-align: middle; text-align: right">
          <div class="is-pulled-right">
            <%= link to: Routes.site_path(@conn, :edit, site), class: "button is-small" do %>
              <span class="icon is-small">
                <i class="fas fa-pen"></i>
              </span>
            <% end %>
            <%= link to: Routes.site_path(@conn, :delete, site), method: :delete, data: [confirm: "Are you sure?"], class: "button is-small is-danger" do %>
              <span class="icon is-small">
                <i class="fas fa-trash"></i>
              </span>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/uprobot_web/templates/site/new.html.eex
<h1 class="is-size-3">New Site</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.site_path(@conn, :create)) %>

lib/uprobot_web/templates/site/show.html.eex
<div class="columns">
  <div class="column is-one-quarter">
    <div class="box" style="border-top: 5px solid <%= if @site.is_active == true, do: "#23d160", else: "#f5f5f5" %>">
      <div class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= @site.name %></strong>
              <br>
              <small><%= @site.url %></small>
              <br>
              <small>Checking per <%= @site.interval %>ms</small>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link(to: Routes.site_path(@conn, :edit, @site), class: "level-item button is-small is-info") do %>
                <span class="icon is-small">
                  <i class="fas fa-edit" aria-hidden="true"></i>
                </span>
                &nbsp;&nbsp;Edit this site
              <% end %>

              <%= link(to: Routes.site_path(@conn, :delete, @site), method: :delete, class: "level-item button is-small is-danger", data: [confirm: "Really?"]) do %>
                <span class="icon is-small">
                  <i class="fas fa-trash" aria-hidden="true"></i>
                </span>
                &nbsp;&nbsp;Delete this site
              <% end %>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <div class="column">
    <%= if length(@site.statuses) > 0 do %>
      <div class="box" style="border-top: 5px solid <%= if Map.get(hd(@site.statuses), :status_code) in 100..400, do: "#23d160", else: "#f5f5f5" %>">
        <div class="media">
          <div class="media-content">
            <div class="content">
              <strong>The last status</strong>
              <br>
              <%= @site.name %> is currently <%= Map.get(hd(@site.statuses), :status_text, "OK!") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="box">
      <div class="media">
        <div class="media-content">
          <div class="content">
            <strong>Timelog</strong>
            <hr>
            <table class="table is-fullwidth is-hoverable">
              <thead>
                <tr>
                  <th><span class="tooltip" data-tooltip="Ping time">Time</span></th>
                  <th><span class="tooltip" data-tooltip="Status code">Code</span></th>
                  <th><span class="tooltip" data-tooltip="Status text">Text</span></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%= for status <- @site.statuses do %>
                  <tr class="has-text-<%= if status.status_code in 100..400, do: "success", else: "danger" %>">
                    <td>
                      <%= status.inserted_at %>
                    </td>
                    <td>
                      <%= status.status_code %>
                    </td>
                    <td>
                      <%= status.status_text %>
                    </td>
                    <td>
                      <%= link(to: Routes.site_status_path(@conn, :delete, @site, status), method: :delete, class: "level-item button is-small is-danger", data: [confirm: "Really?"]) do %>
                        <span class="icon is-small">
                          <i class="fas fa-trash" aria-hidden="true"></i>
                        </span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>